name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 在主分支推送时触发
    paths:
      - docker/debian-trixie/armel/**  # 指定路径
  workflow_dispatch:
jobs:
  build:
    name: Build and Push debian-trixie-armel Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/debian-trixie/armel
          file: ./docker/debian-trixie/armel/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/builder-debian-trixie-armel:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/builder-debian-trixie-armel:latest
          push: true

      - name: Remove cache after build
        run: |
          rm -rf /tmp/.buildx-cache
